source 'https://rubygems.org'
ruby '3.2.3'

gem 'rails', '~> 7.0.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 5.0'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'rack-cors'
gem 'jbuilder'
gem "tzinfo-data"
gem "pg", "~> 1.5"


